# Generated by Django 5.0.2 on 2024-04-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='entrees',
            field=models.ManyToManyField(related_name='entree_carts', to='food.entree'),
        ),
    ]
