# Generated by Django 5.0.2 on 2024-04-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_cart_quantity_cartitem_entreecartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreecartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='entreecartitem',
            name='entree',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='EntreeCartItem',
        ),
    ]
