# Generated by Django 5.0.2 on 2024-04-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_remove_entreecartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
